# Generated by Django 3.2 on 2024-05-27 06:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerticket',
            name='message',
            field=ckeditor.fields.RichTextField(default='', verbose_name='پاسخ پیام'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='message',
            field=ckeditor.fields.RichTextField(verbose_name='پیام شما'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, help_text='در باره خودتان در حدود 300 کلمه بنویسید', max_length=300, null=True, verbose_name='درباره من'),
        ),
    ]
