# Generated by Django 5.1.3 on 2024-12-08 12:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerticket',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='پاسخ پیام'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='پیام شما'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='در باره خودتان در حدود 300 کلمه بنویسید', max_length=300, null=True, verbose_name='درباره من'),
        ),
    ]
