# Generated by Django 5.1.3 on 2024-11-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='شماره همراه')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ')),
                ('time', models.TimeField(auto_now_add=True, null=True, verbose_name='زمان')),
                ('num_attendees', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد اعضای جلسه')),
                ('gender_attendees', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='جنسیت حضار')),
                ('education_min_attendees', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='حداقل سواد حاضران')),
                ('education_max_attendees', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='حداکثر سواد حاضران')),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='شهر')),
                ('topic', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='موضوع روضه')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات ثبت شده',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
