# Generated by Django 5.1.3 on 2024-11-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_order_options_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('uc', 'انجام نشده'), ('c', 'انجام شده')], default='uc', max_length=2, verbose_name='وضعیت'),
        ),
    ]
