# Generated by Django 5.1.3 on 2024-11-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_chatuser_fromuser_channelmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatuser',
            old_name='type',
            new_name='m_type',
        ),
    ]
