# Generated by Django 5.1.3 on 2024-11-11 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_rename_type_chatuser_m_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='related_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.channelmessage'),
        ),
    ]
