# Generated by Django 5.1.3 on 2024-11-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_order_related_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='نام')),
                ('family', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name='سن')),
                ('phone', models.CharField(blank=True, default='+98912345689', max_length=12, null=True, verbose_name='شماره همراه')),
                ('address', models.CharField(blank=True, default='ثبت نشده', max_length=500, null=True, verbose_name='آدرس')),
                ('education_attendees', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='تحصیلات سخنران')),
                ('gender_attendees', models.CharField(blank=True, choices=[('m', 'مرد'), ('w', 'زن')], default='m', max_length=1, null=True, verbose_name='جنسیت')),
                ('register_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ثبت نام')),
                ('total_number_of_lectures', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد کل روضه های انجام شده')),
                ('today_number_of_lectures', models.IntegerField(blank=True, default=0, null=True, verbose_name='روضه های انجام شده امروز')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='وضعیت')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده؟')),
            ],
            options={
                'verbose_name': 'سخنران',
                'verbose_name_plural': 'سخنران ها',
                'ordering': ['name', 'family', 'age', 'total_number_of_lectures'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='related_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.channelmessage', verbose_name='پیام مرتبط'),
        ),
    ]
