# Generated by Django 5.1.3 on 2024-11-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_speaker_alter_order_related_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='education_attendees',
            field=models.CharField(blank=True, default='نا مشخص', max_length=255, null=True, verbose_name='تحصیلات سخنران'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='gender_attendees',
            field=models.CharField(choices=[('m', 'مرد'), ('w', 'زن')], default='m', max_length=1, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده؟'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
    ]
