# Generated by Django 5.1.3 on 2024-11-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_order_date_alter_order_time_orderspeaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_assign',
            field=models.BooleanField(default=False, verbose_name='مرتبط شده؟'),
        ),
    ]
