# Generated by Django 5.1.3 on 2024-11-13 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_orderspeaker_is_message_send_alter_orderspeaker_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_message_send',
            field=models.BooleanField(default=False, verbose_name='پیام ارسال شده؟'),
        ),
        migrations.AlterField(
            model_name='orderspeaker',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 13, 7, 18, 4, 799556, tzinfo=datetime.timezone.utc), null=True, verbose_name='زمان ثبت'),
        ),
    ]
