# Generated by Django 5.1.3 on 2024-11-13 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_orderspeaker_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='today_number_of_lectures',
        ),
        migrations.AlterField(
            model_name='orderspeaker',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 13, 7, 51, 30, 901162, tzinfo=datetime.timezone.utc), null=True, verbose_name='زمان ثبت'),
        ),
    ]
