# Generated by Django 5.1.3 on 2024-12-13 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_alter_order_is_selected_alter_orderspeaker_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_selected',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='gender_attendees',
        ),
        migrations.AddField(
            model_name='speaker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='حذف شده؟'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت فعالیت'),
        ),
        migrations.CreateModel(
            name='AssignOrderSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='زمان ثبت')),
                ('is_message_send', models.BooleanField(default=False, verbose_name='پیام ارسال شده؟')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.order', verbose_name='سفارش')),
                ('related_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.channelmessage', verbose_name='پیام مرتبط')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.speaker', verbose_name='سخنران')),
            ],
            options={
                'verbose_name': 'سخنران_سفارش',
                'verbose_name_plural': 'اختصاص سفارش به سخنران',
            },
        ),
        migrations.CreateModel(
            name='SelectOrderSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ManyToManyField(blank=True, null=True, related_name='order_set', to='application.order', verbose_name='سفارش')),
                ('speaker', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='application.speaker', verbose_name='سخنران')),
            ],
            options={
                'verbose_name': 'انتخاب سفارش',
                'verbose_name_plural': 'سفارشات انتخاب شده',
            },
        ),
        migrations.DeleteModel(
            name='OrderSpeaker',
        ),
    ]
